fix: azure yml

diff --git a/ci-cd/AzureDevOps/azure-pipelines.yml b/ci-cd/AzureDevOps/azure-pipelines.yml
--- a/ci-cd/AzureDevOps/azure-pipelines.yml
+++ b/ci-cd/AzureDevOps/azure-pipelines.yml
@@ -7,6 +7,7 @@
 #
 # The following values should be added as environment variables with the key being secret
 #    SPLXAI_TARGET_ID: the Target ID of the pre defined Target, from SplxAI Probe, Target Settings
+#    SPLXAI_WORKSPACE_ID: the Workspace ID of the pre defined Target, from SplxAI Probe (can be found in the URL when viewing the Target - e.g 163 in https://probe.splx.ai/w/163/target/000)
 #    SPLXAI_API_KEY: the API key generated from SplxAI Probe, Account Settings
 #    SPLXAI_PLATFORM_URL: the SplxAI url that you login to (e.g https://probe.splx.ai/ or https://us.probe.splx.ai/)
 #    SPLXAI_API_URL: the SplxAI url that you login to (e.g https://api.probe.splx.ai/ or https://api.us.probe.splx.ai/)
@@ -16,52 +17,54 @@
 #
 
 trigger:
-- main
+  - main
 
 pool:
   vmImage: ubuntu-latest
 
 variables:
-- name: SPLXAI_TARGET_ID
-  value: 000
-- name: SPLXAI_PLATFORM_URL
-  value: "https://probe.splx.ai"
-- name: SPLXAI_API_URL
-  value: "https://api.probe.splx.ai"
+  - name: SPLXAI_TARGET_ID
+    value: 000
+  - name: SPLXAI_WORKSPACE_ID
+    value: 000
+  - name: SPLXAI_PLATFORM_URL
+    value: "https://probe.splx.ai"
+  - name: SPLXAI_API_URL
+    value: "https://api.probe.splx.ai"
 
 steps:
-- script: |
-    sudo apt-get -qq update
-    sudo apt-get install -y jq
-    
-    echo "###### Start SplxAI Test Run #######"
-    REQUEST_BODY=$(cat <<-EOF
-        {
-            "targetId": $SPLXAI_TARGET_ID,
-            "probeIds": [1],
-            "name": "AZDO CI/CD Test Run"
-        }
-    EOF
-    )
+  - script: |
+      sudo apt-get -qq update
+      sudo apt-get install -y jq
 
-    RESPONSE=$(curl -s --request POST \
-      --url $SPLXAI_API_URL/api/v2/test-run/trigger \
-      --header 'Content-Type: application/json' \
-      --header "X-Api-Key: $SPLXAI_API_KEY" \
-      --data "$REQUEST_BODY")
-    
-    TEST_RUN_ID=$(echo $RESPONSE | jq -r '.testRunId')
-    if [ -z "$TEST_RUN_ID" ]; then
-      echo "Error: Failed to trigger Test Run!"
-      echo "Response: $RESPONSE"
-      exit 1
-    fi
-    
-    echo "###### Triggered SplxAI Test Run #######"
-    echo "=> Click on the link below to see the Test Run results"
-    echo "=> https://probe.splx.ai/target/$SPLXAI_TARGET_ID/test-run-history/$TEST_RUN_ID"
-  
-  env:
-    SPLXAI_API_KEY: $(SPLXAI_API_KEY) # add your secret vaeriable https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops
+      echo "###### Start SplxAI Test Run #######"
+      REQUEST_BODY=$(cat <<-EOF
+          {
+              "targetId": $SPLXAI_TARGET_ID,
+              "probeIds": [1],
+              "name": "AZDO CI/CD Test Run"
+          }
+      EOF
+      )
 
-  displayName: 'SplxAI Test'
+      RESPONSE=$(curl -s --request POST \
+        --url $SPLXAI_API_URL/api/workspaces/$SPLXAI_WORKSPACE_ID/test-run/trigger \
+        --header 'Content-Type: application/json' \
+        --header "X-Api-Key: $SPLXAI_API_KEY" \
+        --data "$REQUEST_BODY")
+
+      TEST_RUN_ID=$(echo $RESPONSE | jq -r '.testRunId')
+      if [ -z "$TEST_RUN_ID" ]; then
+        echo "Error: Failed to trigger Test Run!"
+        echo "Response: $RESPONSE"
+        exit 1
+      fi
+
+      echo "###### Triggered SplxAI Test Run #######"
+      echo "=> Click on the link below to see the Test Run results"
+      echo "=> https://probe.splx.ai/w/$SPLXAI_WORKSPACE_ID/target/$SPLXAI_TARGET_ID/test-runs/$TEST_RUN_ID"
+
+    env:
+      SPLXAI_API_KEY: $(SPLXAI_API_KEY) # add your secret vaeriable https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops
+
+    displayName: "SplxAI Test"
